// actions/types.js

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';


export const GET_MESAS = 'GET_PRODUCTS';
export const FETCH_MESAS_LOADING = 'FETCH_MESAS_LOADING';
export const FETCH_MESAS_SUCCESS = 'FETCH_MESAS_SUCCESS';
export const FETCH_MESAS_ERROR = 'FETCH_MESAS_ERROR';

//export const FETCH_MESAS_ESTADO_LOADING = 'FETCH_MESAS_ESTADO_LOADING';
//export const FETCH_MESAS_ESTADO_SUCCESS = 'FETCH_MESAS_ESTADO_SUCCESS';
//export const FETCH_MESAS_ESTADO_ERROR = 'FETCH_MESAS_ESTADO_ERROR';

export const FETCH_MESAS_CONSUMO_LOADING = 'FETCH_MESAS_CONSUMO_LOADING';
export const FETCH_MESAS_CONSUMO_SUCCESS = 'FETCH_MESAS_CONSUMO_SUCCESS';
export const FETCH_MESAS_CONSUMO_ERROR = 'FETCH_MESAS_CONSUMO_ERROR';

export const ASSIGN_PRODUCTS_TO_MESA = 'ASSIGN_PRODUCTS_TO_MESA';

export const CREATE_MESA_REQUEST = 'CREATE_MESA_REQUEST';
export const CREATE_MESA_SUCCESS = 'CREATE_MESA_SUCCESS';
export const CREATE_MESA_FAILURE = 'CREATE_MESA_FAILURE';

export const ADD_MESA = 'ADD_MESA';
export const UPDATE_MESA = 'UPDATE_MESA';
export const DELETE_MESA = 'DELETE_MESA';

// TYPES PARA ALMACENAR LOS DATOS TEMPORALES DE CONSUMO
export const SET_TEMP_MESA_DATA = "SET_TEMP_MESA_DATA";
export const CLEAR_TEMP_MESA_DATA = "CLEAR_TEMP_MESA_DATA";

export const SET_ALL_TEMP_MESA_DATA = "SET_ALL_TEMP_MESA_DATA";

